Resources/doc/index.rst

Added a caution block before the load command is introduced, warning the reader that, by default, all data is removed from every table by the load command. I accidentally blew away a development database thinking only the tables to which my fixtures applied would be purged.

Documentation: load with append option

---

Command/LoadDataFixturesDoctrineCommand.php

Use a lowercase `y` and uppercase `N` to indicate that no is the default option.

Clarify default option in dialog confirmation

---

Command/LoadDataFixturesDoctrineCommand.php

The command ```fixtures``` option is documented as below:
> The directory or file to load data fixtures from.
In fact, it's currently impossible to load fixtures from a file.
This PR needs doctrine/data-fixtures#106 to be relevant.

Allow fixtures loading from a single file

---

Command/LoadDataFixturesDoctrineCommand.php

In tandem with my pull request on doctrine/data-fixtures this allows a user to select whether they want to load fixtures in a single transaction or one transaction per fixture

This provides an option to use one transaction per fixture file

---

EmptyFixture.php
Fixture.php
README.markdown
Resources/doc/index.rst

Doctrine is a great piece of software, but some developers from the Symfony community always tell us that sometimes it's too complex and cumbersome. That's why we'd like to improve the "developer experience" of Doctrine and smooth out some of its rough edges.
This pull request contains our first proposal to **simplify the creation of data fixtures**. As you can see, the idea is to provide an optional base class for data fixtures. Even if the code changes are minimal, the updated docs show all the simplifications that it allows.
Thanks for taking this PR into consideration!

Improve the DX of the DoctrineFixturesBundle

---

Command/LoadDataFixturesDoctrineCommand.php

It would be helpful to handle fixtures automatically(without specifying of path), in applications those are using MicroKernelTrait or similar ones, those do not define bundles in itself.
Small fix great profits.

Add kernel root directory to fixtures location paths

---

DependencyInjection/DoctrineFixturesExtension.php
Resources/config/services.xml

Fixes #204
> Auto-registration of the command "Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand" is deprecated since Symfony 3.4 and won't be supported in 4.0. Use PSR-4 based service discovery instead

Fix sf3.4 command autoregistration deprecation

---

UPGRADE.md

This is needed when upgrading a Symfony app, that will not automatically import the new default configuration for fixture classes autowiring.

Add example for fixture autowiring

---

Resources/doc/index.rst

I got this idea that it may be better to use constants to reference objects between fixtures. Instead of using "magic" strings (which can be renamed in one place or can contain a typo), constant creates a statically analyzable reference (so an IDE allows you to click through to the other fixture, or some other tool can verify that the reference is correct).

[DOC] Recommend constants for sharing objects between fixtures

---

.travis.yml
Tests/IntegrationTest.php
composer.json

This PR fixes the current build failures:
* Introduce direct dependency to PHPUnit to avoid failures due to 
https://github.com/symfony/symfony/pull/29263
* Fix kernel deprecation as highlighted in #260 
* Add PHP 7.3 to the test matrix (closes #259)

Fix build failures

---

Command/LoadDataFixturesDoctrineCommand.php

Extracted from #260 since the breakage occurs in 3.0 (and #260 will be 3.1).

Fix confirmation prompt

---

Command/LoadDataFixturesDoctrineCommand.php

Fixes #266 (cc @garak). #263 broke running the fixture command when using the `non-interactive` command-line option. This PR ensures that fixtures are always loaded in non-interactive mode while retaining the original behaviour in interactive mode.

Fix fixture loading in non-interactive mode

---

.travis.yml
Loader/SymfonyFixturesLoader.php
composer.json

* Branch alias is now 3.1.x
* Drop PHP < 7.1
* Drop support for older versions of data-fixtures and DoctrineBundle

Drop old stuff

---

Command/LoadDataFixturesDoctrineCommand.php
DependencyInjection/CompilerPass/FixturesCompilerPass.php
FixtureGroupInterface.php
Loader/SymfonyFixturesLoader.php
Resources/doc/index.rst
Tests/Fixtures/FooBundle/DataFixtures/OtherFixtures.php
Tests/Fixtures/FooBundle/DataFixtures/WithDependenciesFixtures.php
Tests/IntegrationTest.php

Hi guys!
This combines the nice work from #255 and #256 to add "groups" of fixtures to be loaded via a `--group=foo` flag on the command.
A fixture can be added to a group either via a `getGroups()` method on the class itself, or a `group` attribute on a service tag. This is very consistent with other patterns in Symfony - e.g. how command names can be set via a static property or as a service tag.
There is a strong IntegrationTest for this feature and I just tried it "in the wild" in a project. It works :).
Replaces #246 and #250.
Cheers!

Add fixture groups via a static method interface or service tags

---

Resources/doc/index.rst

Most changes are cosmetic ... but I also promoted Symfony4/Flex more in the docs.

Updated docs to match the style of the other Symfony docs

---

Command/LoadDataFixturesDoctrineCommand.php
Resources/config/services.xml
Tests/IntegrationTest.php

```
1x: The "Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand" constructor expects a "Doctrine\Common\Persistence\ManagerRegistry" instance as first argument, not passing it will throw a \TypeError in DoctrineBundle 2.0.
1x in Application::run from Symfony\Bundle\FrameworkBundle\Console
1x: The "Doctrine\Bundle\DoctrineBundle\Command\DoctrineCommand::getContainer()" method is deprecated and will be removed in DoctrineBundle 2.0.
1x in Application::run from Symfony\Bundle\FrameworkBundle\Console
```

Fix deprecation on load fixtures command

---

composer.json

This bundle only provides fixture loading for Doctrine ORM, so it should be a hard dependency: installing it without ORM is possible but would lead to errors when running the command, so it makes sense to make this a required dependency.

Add missing dependency to doctrine/orm

---

Command/LoadDataFixturesDoctrineCommand.php
Tests/Command/LoadDataFixturesDoctrineCommandTest.php
phpunit.xml.dist

Supersedes #283.
This PR:
* fixes an invalid call to `DoctrineCommand::__construct` on lower DoctrineBundle versions
* removes a call to the deprecated `getContainer()` method if the `getDoctrine()` method is present.
Since this is a bugfix release for 3.2, the dependency to DoctrineBundle can't really be bumped, as it will simply make this bugfix ineligible during version resolution for users of older DoctrineBundle versions. Thus, we work with `method_exists` to ensure the calls are handled correctly, removing this workaround in the next minor release where we'll properly bump the DoctrineBundle dependency.

Fix deprecations in fixture command

---

Command/LoadDataFixturesDoctrineCommand.php
composer.json

After #285, we can drop old bundle versions in the next minor release.

Drop support for older versions of DoctrineBundle

---

Tests/IntegrationTest.php
composer.json

Remove the dependency on the doctrine bundle (as the only use was in the command, and none of the helpers from the `DoctrineCommand` were used), and replace the framework-bundle dependency with the config, dic and http-kernel instead.
I kept the fw-bundle dependency in dev env, because the tests need it.
Should fix #224

Split the framework-bundle dependency

---

Resources/doc/index.rst

Since ee5eb61, Doctrine\Bundle\FixturesBundle\Fixture does not implement ContainerAwareInterface anymore and thus, $container is not part of this class anymore.
See https://github.com/doctrine/DoctrineFixturesBundle/commit/ee5eb61#diff-8490d6a88059c82df2c98e6f2d0918d2

$container is no longer available in Fixture class
